# ===================================================================
#      Simplified GitHub Actions Workflow for mcMMO-Classic
#
# Goal: Compile the default branch ('master') of the forked repo.
# This version removes all branch/tag selection for simplicity.
# ===================================================================

# 1. Workflow Name
name: Build Default Branch

# 2. Workflow Triggers
on:
  # Allows manual triggering from the GitHub Actions UI
  workflow_dispatch:

  # Optional: Trigger automatically on pushes to the 'master' branch
  push:
    branches: [ "master" ]

# 3. Jobs
jobs:
  build:
    # Set the job to run on the latest Ubuntu environment
    runs-on: ubuntu-latest

    # Steps to be executed
    steps:
      # Step 1: Checkout the source code from the 'master' branch
      - name: 1. Checkout Code
        uses: actions/checkout@v4
        with:
          # We explicitly checkout the 'master' branch
          ref: 'master'

      # Step 2: Set up JDK 8 for compilation
      - name: 2. Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      # Step 3: Compile the project using Maven
      - name: 3. Compile with Maven
        run: mvn -B clean package -DskipTests

      # Step 4: List the build output for debugging
      - name: 4. Verify Build Output
        run: |
          echo "Listing contents of the target directory:"
          ls -l target/

      # Step 5: Upload the compiled .jar as an artifact
      - name: 5. Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcMMO-Classic-Build-from-master
          path: target/mcMMO-*.jar
          retention-days: 7
